server:
  port: 8081
  servlet:
    context-path: /blog
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
mybatis:
  config-location: classpath:/config/mybatis.xml
  mapper-locations: classpath:/mapper/*.xml
logging:
  config: classpath:log4j2.xml

#缓存

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql




