INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (1, 1, '张三', 'a@1.com', '127.0.0.1', '评论评论', '2018-05-28 15:43:27');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (2, 1, '里斯', 'a@1.com', '127.0.0.1', '评论评论里斯李四', '2018-05-28 15:43:44');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (3, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (4, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (5, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (6, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (7, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (8, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (9, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (10, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (11, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (12, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (13, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (14, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (15, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (16, 1, '张三', '3@163.com', NULL, NULL, '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (17, 1, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (18, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (19, 1, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (20, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (21, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (22, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (23, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (24, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (25, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (26, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (27, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (28, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (29, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (30, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 00:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (31, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (32, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (33, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (34, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (35, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (36, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (37, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (38, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (39, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (40, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-02-02 17:00:00');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (41, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 03:12:16');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (42, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-29 19:13:56');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (43, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-29 19:16:47');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (44, 2, '张三', '3@163.com', NULL, '内容评论，评论内容', '2018-05-30 10:50:16');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (45, 2, '李四', '3445@qq.com', NULL, '华人融化 杀杀杀', '2018-05-30 13:33:56');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (46, 2, '李四', '3445@qq.com', NULL, '华人融化 杀杀杀杀杀杀', '2018-05-30 13:34:13');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (47, 2, 'ss', 'sss@33.com', NULL, '杀杀杀', '2018-05-30 13:35:16');
INSERT INTO `comment`(`code`, `document_code`, `name`, `email`, `ip`, `content`, `create_time`) VALUES (48, 2, '我的名字就是长', '12@22.com', NULL, '内容我的内容就是长', '2018-05-30 13:35:56');
