server:
  port: 8082
spring:
  application:
    name: demo2-config-server
  cloud:
    config:
      server:
        git:
          uri: ssh://git@47.52.239.55/home/git/youzule/springcloud/.git
          search-paths:
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/